[package]
name = "lume_ir"
version.workspace = true
edition.workspace = true

[dependencies]
lume_ast = { path = "../lume_ast" }
lume_diagnostics = { path = "../lume_diagnostics" }
lume_hir = { path = "../lume_hir" }
lume_parser = { path = "../lume_parser" }
lume_span = { path = "../lume_span" }

[lib]
path = "src/lib.rs"
