[package]
name = "lume_codegen_wasm"
version.workspace = true
edition.workspace = true

[dependencies]
inkwell.workspace = true
lume_ast = { path = "../lume_ast" }
lume_ir = { path = "../lume_ir" }

[dev-dependencies]
lume_hir = { path = "../lume_hir" }
lume_parser = { path = "../lume_parser" }

[lib]
path = "src/lib.rs"
